ALTER TABLE "Post"
    DROP COLUMN IF EXISTS updated_at;
ALTER TABLE "Post"
    DROP COLUMN IF EXISTS title;
ALTER TABLE "Post"
    ALTER COLUMN tags TYPE TEXT[];
ALTER TABLE "Post"
    ALTER COLUMN tags SET DEFAULT ARRAY[]::TEXT[];