ALTER TABLE "Post"
    ADD COLUMN updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NOW();
ALTER TABLE "Post"
    ADD COLUMN title TEXT NOT NULL;
ALTER TABLE "Post"
    ALTER COLUMN tags TYPE VARCHAR(255);